WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e4c095450>: Failed to establish a new connection: [Errno 111] Connection refused')': /cdb/api/auth/login
WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e4c095a10>: Failed to establish a new connection: [Errno 111] Connection refused')': /cdb/api/auth/login
WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7e4c0a65d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /cdb/api/auth/login
